import type { ModelInfo } from './api';

export const IMAGE_MODELS: ModelInfo[] = [
  {
    id: 'cf/@cf/black-forest-labs/flux-2-klein-9b',
    object: 'model',
    owned_by: 'cloudflare',
    description: 'FLUX.2 Klein 9B — high quality, fast inference',
    max_image_size: '1024x1024',
    step_range: [1, 4],
    cfg_range: [1, 5],
    max_batch: 4,
  },
  {
    id: 'cf/@cf/black-forest-labs/flux-2-klein-4b',
    object: 'model',
    owned_by: 'cloudflare',
    description: 'FLUX.2 Klein 4B — lightweight, fast',
    max_image_size: '1024x1024',
    step_range: [1, 4],
    cfg_range: [1, 5],
    max_batch: 4,
  },
  {
    id: 'cf/@cf/black-forest-labs/flux-2-dev',
    object: 'model',
    owned_by: 'cloudflare',
    description: 'FLUX.2 Dev — high quality development model',
    max_image_size: '1024x1024',
    step_range: [1, 8],
    cfg_range: [1, 5],
    max_batch: 4,
  },
  {
    id: 'cf/@cf/leonardo/lucid-origin',
    object: 'model',
    owned_by: 'cloudflare',
    description: 'Leonardo Lucid Origin — artistic generation',
    max_image_size: '1024x1024',
    step_range: [1, 8],
    cfg_range: [1, 10],
    max_batch: 4,
  },
  {
    id: 'cf/@cf/leonardo/phoenix-1.0',
    object: 'model',
    owned_by: 'cloudflare',
    description: 'Leonardo Phoenix 1.0 — versatile image generation',
    max_image_size: '1024x1024',
    step_range: [1, 8],
    cfg_range: [1, 10],
    max_batch: 4,
  },
  {
    id: 'cf/@cf/black-forest-labs/flux-1-schnell',
    object: 'model',
    owned_by: 'cloudflare',
    description: 'FLUX.1 Schnell — ultra fast generation',
    max_image_size: '1024x1024',
    step_range: [1, 4],
    cfg_range: [1, 5],
    max_batch: 8,
  },
  {
    id: 'cf/@cf/bytedance/stable-diffusion-xl-lightning',
    object: 'model',
    owned_by: 'cloudflare',
    description: 'SDXL Lightning — fast SDXL variant',
    max_image_size: '1024x1024',
    step_range: [1, 4],
    cfg_range: [1, 5],
    max_batch: 4,
  },
  {
    id: 'cf/@cf/lykon/dreamshaper-8-lcm',
    object: 'model',
    owned_by: 'cloudflare',
    description: 'DreamShaper 8 LCM — artistic, dreamy style',
    max_image_size: '1024x1024',
    step_range: [1, 8],
    cfg_range: [1, 10],
    max_batch: 4,
  },
  {
    id: 'cf/@cf/runwayml/stable-diffusion-v1-5-img2img',
    object: 'model',
    owned_by: 'cloudflare',
    description: 'SD v1.5 Img2Img — image-to-image translation',
    max_image_size: '1024x1024',
    step_range: [1, 50],
    cfg_range: [1, 20],
    max_batch: 4,
  },
  {
    id: 'cf/@cf/runwayml/stable-diffusion-v1-5-inpainting',
    object: 'model',
    owned_by: 'cloudflare',
    description: 'SD v1.5 Inpainting — masked area replacement',
    max_image_size: '1024x1024',
    step_range: [1, 50],
    cfg_range: [1, 20],
    max_batch: 4,
  },
  {
    id: 'cf/@cf/stabilityai/stable-diffusion-xl-base-1.0',
    object: 'model',
    owned_by: 'cloudflare',
    description: 'SDXL Base 1.0 — high quality, versatile',
    max_image_size: '1024x1024',
    step_range: [1, 50],
    cfg_range: [1, 20],
    max_batch: 4,
  },
];

export function getCloudflareImageModels(): ModelInfo[] {
  return IMAGE_MODELS;
}
